apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- virtual_service.yaml
images:
- name: gcr.io/mmarr-test-project/hello-world
  newTag: 3dc8de25354d14d84a9fedb5b7bd54c66ab810f7
