apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- virtual_service.yaml
images:
- name: gcr.io/mmarr-test-project/hello-world
  newTag: d4bd9190b01820cda1a30b22ef28bdce9bb119d3
